[package]
name = "auto_sitemap"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
url = "2.4.0"
xml = "0.8.10"
yaserde = { version="0.8.0", features = ["yaserde_derive"] }
yaserde_derive = "0.8.0"

[dev-dependencies]
pretty_assertions = "1.4.0"
