name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os:
          - name: Ubuntu
            runner: ubuntu-latest
          - name: macOS
            runner: macOS-latest
          - name: Windows
            runner: windows-latest
        rust: [stable, beta, nightly]

    runs-on: ${{ matrix.os.runner }}
    name: ${{ matrix.os.name }} - ${{ matrix.rust }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        components: rustfmt, clippy
        override: true

    - name: Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Check code formatting
      run: cargo fmt --all -- --check

    - name: Check with Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo test --verbose
